import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { useConnect, useAccount, useConfig, useChainId } from 'wagmi'
import {disconnect} from '@wagmi/core'

export default function Home() {
  const { connect, connectors } = useConnect()
  const { address, chainId, status } = useAccount()
  const config = useConfig()
  const d = useChainId()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {connectors.map((connector) => (
        <button key={connector.id} onClick={() => connect({ connector })}>
          {connector.name}
        </button>
      ))}
      {address && <button onClick={()=>disconnect(config)} >Disconnect</button>}
      <div>Address: {address}</div>
      <div>Chain ID: {chainId}</div>
      <div>Status: {status}</div>
      </main>
    </>
  )
}
